import type { Metadata } from "next";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll";
import Header from "./components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="layout-grid relative">
        <SmoothScroll>
          <div className="layout-grid absolute top-0 left-0 w-full h-full pointer-events-none">
            {[...Array(7)].map((_, index) => (
              <div key={index} className={`-z-10 pointer-events-none relative w-full before:w-full before:absolute ${index === 0 ? "" : "before:border-l"}  before:border-black before:border-opacity-15 before:h-full ${index === 6 ? "before:border-r" : ""}`}></div>
            ))}
          </div>

          <Header />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
